# checkmarx-specific related configuration
# every value in this section is optional 
checkmarx: 
  # configure the checkmarx scan parameters for scanning this specific project
  scan:
    # configure the checkmarx scan configurations for scanning this specific project
    configs:
      # configure the SAST related configurations this specific project
      sast:
        # configure the SAST preset name used for this specific project
        presetName: 'ASA Premium' 
        fastScanMode: 'false'
        # configure if this specific project will be run incrementally or will it run a full scan
        incremental: 'false'
        languageMode: 'multi'
        filter: '!*.java,!*.cpp'
        engineVerbose: 'true'
      sca:
        filter: '!*.cpp'
        exploitablePath: 'true'
        lastSastScanTime: '10'
      kics:
        filter: '*.java'
        platforms: 'Ansible,CloudFormation,Dockerfile'
